name: Elf Test CI

on: 
  push:
    branches: [mocklibc]
  pull_request:
    branches: [mocklibc]

env:
  qemu-version: 8.2.0
  rust-toolchain: nightly-2024-12-25

jobs:
  loader-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [riscv64]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust-toolchain }}
          components: rust-src
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-binutils
      - uses: ./.github/workflows/actions/setup-qemu
        with:
          qemu-version: ${{ env.qemu-version }}
      - uses: ./.github/workflows/actions/setup-musl
        with:
          arch: ${{ matrix.arch }}
      - name: hello static build
        run: python build.py static
        working-directory: ./payload/hello_app
      - name: run tests
        run: |
          make defconfig ARCH=${{ matrix.arch }}
          make A=examples/loader ARCH=${{ matrix.arch }} run
      - name: hello dynamic build
        run: python build.py dynamic
        working-directory: ./payload/hello_app
      - name: run tests
        run: |
          make defconfig ARCH=${{ matrix.arch }}
          make A=examples/loader ARCH=${{ matrix.arch }} run
      - name: printf dynamic build
        run: python build.py printf
        working-directory: ./payload/printf_app
      - name: run tests
        run: |
          make defconfig ARCH=${{ matrix.arch }}
          make A=examples/loader ARCH=${{ matrix.arch }} run
      - name: pthread dynamic build
        run: python build.py pthread
        working-directory: ./payload/pthread_app
      - name: run tests
        run: |
          make defconfig ARCH=${{ matrix.arch }}
          make A=examples/loader ARCH=${{ matrix.arch }} run
